---
title: "Shiny"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(ggridges)
library(plotly)
library(shiny)
```

```{r}
instacart = read_csv("../data/instacart_train_data.csv.zip")

```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
departments = instacart %>% distinct(department) %>% pull()
checkboxGroupInput(inputId = "obs",
                   label = h3("Observations to view:"), choices = departments,
                   selected = c("beverages","dairy eggs", "produce", "deli", "snacks"))
```


```{r}
sliderInput("rank", label = h3("Choose rank range"), min = 1, 
        max = 21, value = c(5, 10))
```


Row 
-----------------------------------------------------------------------

### Items ordered in each department

```{r}
renderPlotly({ 
  instacart %>%
  group_by(department) %>%
  summarize(items_ordered = n()) %>%
  mutate(depart_rank = min_rank(desc(items_ordered))) %>%
  arrange(depart_rank) %>%
<<<<<<< HEAD
  filter(depart_rank %in% input$rank[1]:input$rank[2]) %>%
=======
>>>>>>> d4e5e1e92d989024529912586c9e18168fd474a9
  mutate(department = fct_reorder(department, items_ordered)) %>%
  filter(depart_rank %in% input$rank[1]:input$rank[2]) %>%
  plot_ly(y = ~items_ordered, x = ~department, type = "bar")
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Order hours for items from each department

```{r}
renderPlotly({
  instacart %>%
  filter(department==input$obs) %>%
  mutate(department = fct_reorder(department, order_hour_of_day, IQR)) %>%
  ggplot(aes(x = department, y = order_hour_of_day, fill = department)) + 
  geom_violin(bw = .6) +
  theme(axis.text.x = element_text(angle = 90))
  })


```


------------------------------------------

### Chart C

```{r}
mean_hour =
  instacart %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_hour = mean(order_hour_of_day)) %>%
  spread(key = order_dow, value = mean_hour) %>%
  gather(key = day, value = mean_hour, "0":"6") %>%
  ggplot(aes(x = day, y = mean_hour, color = day)) +
  geom_boxplot()

ggplotly(mean_hour)

```

